analysis:
  chunk_size: 20
  num_features: 50
  num_samples: 1000
  random_seed: 42
explanation_method:
  method: lime
model:
  model_type: TabNet
other:
  max_test_points: 200
paths:
  data_path: /home/grotehans/xai_locality/data/TabNet_MiniBooNE_normalized_data.pt
  model_path: /home/grotehans/xai_locality/pretrained_models/TabNet/MiniBooNE/TabNet_normalized_binary_MiniBooNE_results.pt
  results_path: /home/grotehans/xai_locality/results/lime/TabNet/MiniBooNE
