explanation_method:
  method: "lime"

paths:
  results_path: "/home/grotehans/xai_locality/results/lime/ExcelFormer/synthetic_data/n_feat50_n_informative2_n_redundant30_n_repeated0_n_classes2_n_samples100000_n_clusters_per_class2_class_sep0.9_flip_y0.01_random_state42"
  data_path: "/home/grotehans/xai_locality/data/synthetic_data/n_feat50_n_informative2_n_redundant30_n_repeated0_n_classes2_n_samples100000_n_clusters_per_class2_class_sep0.9_flip_y0.01_random_state42_normalized_tensor_frame.pt"
  model_path: "/home/grotehans/xai_locality/pretrained_models/ExcelFormer/synthetic_data/ExcelFormer_n_feat50_n_informative2_n_redundant30_n_repeated0_n_classes2_n_samples100000_n_clusters_per_class2_class_sep0.9_flip_y0.01_random_state42_results.pt"
# Model and method configuration
model:
  model_type: "ExcelFormer"

# Analysis parameters
analysis:
  distance_measure: "euclidean"
  max_frac: 0.05
  num_frac: 50
  random_seed: 42
  chunk_size: 100

# Other parameters
other:
  max_test_points: 200
