explanation_method:
  method: "lime"

paths:
  results_path: "/home/grotehans/xai_locality/results/lime/MLP/MiniBooNE"
  data_path: "/home/grotehans/xai_locality/data/MLP_MiniBooNE_normalized_data.pt"
  model_path: "/home/grotehans/xai_locality/pretrained_models/MLP/MiniBooNE/MLP_normalized_binary_MiniBooNE_results.pt"
                                
model: 
  model_type: "MLP"

# Analysis parameters
analysis:
  max_frac: 0.05
  num_frac: 100