explanation_method:
  method: "lime"

paths:
  results_path: "/home/grotehans/xai_locality/results/gradient_methods/integrated_gradient/excelformer/jannis"
  data_path: "/home/grotehans/xai_locality/data/ExcelFormer_medium_6_normalized_data.pt"
  model_path: "/home/grotehans/xai_locality/pretrained_models/excelformer/jannis/ExcelFormer_normalized_binary_medium_6.pt"
                                
model: 
  model_type: "excelformer"

# Analysis parameters
analysis:
  max_frac: 0.05
  num_frac: 100