explanation_method:
  method: "lime"

paths:
  results_folder: "/home/grotehans/xai_locality/results/lime/LightGBM/synthetic_data"
  model_folder: "/home/grotehans/xai_locality/pretrained_models/LightGBM/synthetic_data"
  data_folder: "/home/grotehans/xai_locality/data/synthetic_data"
  setting: "n_feat50_n_informative2_n_redundant30_n_repeated0_n_classes2_n_samples100000_n_clusters_per_class2_class_sep0.9_flip_y0.01_random_state42"

model: 
  model_type: "LightGBM"

# Analysis parameters
analysis:
  chunk_size: 1000