explanation_method:
  method: "lime"
paths:
  results_folder: "/home/grotehans/xai_locality/results/lime/LightGBM/synthetic_data"
  model_folder: "/home/grotehans/xai_locality/pretrained_models/LightGBM/synthetic_data"
  data_folder: "/home/grotehans/xai_locality/data/synthetic_data"
model: 
  model_type: "LightGBM"
# Analysis parameters
analysis:
  chunk_size: 1000
