explanation_method:
  method: "lime"

paths:
  results_path: "/home/grotehans/xai_locality/results/lime/Trompt/jannis"
  data_path: "/home/grotehans/xai_locality/data/Trompt_jannis_normalized_data.pt"
  model_path: "/home/grotehans/xai_locality/pretrained_models/Trompt/jannis/Trompt_normalized_binary_jannis.pt"
                                
model: 
  model_type: "Trompt"

# Analysis parameters
analysis:
  max_frac: 0.05
  num_frac: 100