explanation_method:
  method: "lime"

paths:
  data_path: "/home/grotehans/xai_locality/data/LightGBM_higgs_normalized_data.pt"
  model_path: "/home/grotehans/xai_locality/pretrained_models/LightGBM/higgs/LightGBM_normalized_binary_higgs_results.pt"
  results_path: "/home/grotehans/xai_locality/results/lime/LightGBM/higgs"
                                
model: 
  model_type: "pt_frame_lgm"

# Analysis parameters
analysis:
  include_trn: true
  include_val: true 
  max_frac: 0.05
  num_frac: 100