explanation_method:
  method: "lime"

paths:
  data_path: "/home/grotehans/xai_locality/data/ExcelFormer_higgs_normalized_data.pt"
  model_path: "/home/grotehans/xai_locality/pretrained_models/ExcelFormer/higgs/ExcelFormer_normalized_binary_higgs_results.pt"
  results_path: "/home/grotehans/xai_locality/results/lime/ExcelFormer/higgs"
                                
model: 
  model_type: "ExcelFormer"

# Analysis parameters
analysis:
  max_frac: 0.05
  num_frac: 100