explanation_method:
  method: "lime"

paths:
  data_path: "/home/grotehans/xai_locality/data/ExcelFormer_large_0_normalized_data.pt"
  model_path: "/home/grotehans/xai_locality/pretrained_models/excelformer/higgs/ExcelFormer_normalized_binary_large_0.pt"
  results_path: "/home/grotehans/xai_locality/results/lime/excelformer/higgs"
                                
model: 
  model_type: "excelformer"

# Analysis parameters
analysis:
  max_frac: 0.05
  num_frac: 100