paths:
  results_path: "/home/grotehans/xai_locality/results/gradient_methods/integrated_gradient/cats_vs_dogs"

# Model and method configuration
model:
  model_type: "binary_inception_v3"
  method: "gradient"
  gradient_method: "IG"

# Analysis parameters
analysis:
  distance_measure: "euclidean"
  max_frac: 0.08
  num_frac: 10
  random_seed: 42
  chunk_size: 4

# Other parameters
other:
  max_test_points: 200
