explanation_method:
  method: "lime"

paths:
  results_path: "/home/grotehans/xai_locality/results/lime/ExcelFormer/MiniBooNE"
  data_path: "/home/grotehans/xai_locality/data/ExcelFormer_MiniBooNE_normalized_data.pt"
  model_path: "/home/grotehans/xai_locality/pretrained_models/ExcelFormer/MiniBooNE/ExcelFormer_normalized_binary_MiniBooNE_results.pt"
                                
model: 
  model_type: "ExcelFormer"

# Analysis parameters
analysis:
  max_frac: 0.05
  num_frac: 100