explanation_method:
  method: "gradient"

paths:
  results_path: "/home/grotehans/xai_locality/results/gradient_methods/integrated_gradient/Trompt/jannis"
  data_path: "/home/grotehans/xai_locality/data/Trompt_jannis_normalized_data.pt"
  model_path: "/home/grotehans/xai_locality/pretrained_models/Trompt/jannis/Trompt_normalized_binary_jannis_results.pt"
# Model and method configuration
model:
  model_type: "Trompt"
  gradient_method: "IG"

# Analysis parameters
analysis:
  distance_measure: "euclidean"
  max_frac: 0.05
  num_frac: 50
  random_seed: 42
  chunk_size: 200

# Other parameters
other:
  max_test_points: 200
