analysis:
  chunk_size: 100
  distance_measure: euclidean
  max_frac: 0.05
  num_frac: 50
  random_seed: 42
explanation_method:
  method: gradient
model:
  gradient_method: IG+SmoothGrad
  model_type: ResNet
other:
  max_test_points: 200
paths:
  data_path: /home/grotehans/xai_locality/data/ResNet_higgs_normalized_data.pt
  model_path: /home/grotehans/xai_locality/pretrained_models/ResNet/higgs/ResNet_normalized_binary_higgs_results.pt
  results_path: /home/grotehans/xai_locality/results/gradient_methods/smoothgrad/ResNet/higgs
